### ISSUE TITLE
Use Weblate for psi-translations

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi-translations#5]
Weblate is a free web-based translation management system.
https://github.com/nijel/weblate-web
http://weblate.org/en/

I would feel much more comfortable to translate Psi using [Weblate](https://hosted.weblate.org/) instead of being a member of @psi-im

**Comment by GreenLunar** [comment]
@nijel, would you like to assist me to integrate https://github.com/GreenLunar/psi-translations with https://hosted.weblate.org/ ?

I want to see if @jkarneges would give his consent to integrate this repository (psi-im/psi-translations) with Weblate.

**Comment by jkarneges** [comment]
This is fine by me.

**Comment by GreenLunar** [comment]
Then I will configure this repository to use Weblate and ask the Weblate staff for help. I will keep /GreenLunar/psi-translations as a backup, in case I mess up something.

**Comment by GreenLunar** [comment]
I do not have access to repository setting. I want to follow the instructions at https://docs.weblate.org/en/latest/admin/continuous.html

**Comment by nijel** [comment]
Dne Fri, 10 Jul 2015 07:25:18 -0700
GreenLunar <notifications@github.com> napsal(a):

> @nijel, would you like to assist me to integrate https://github.com/GreenLunar/psi-translations with https://hosted.weblate.org/ ?

Do you really want to translate this one? I see it's forked from
psi-im/psi-translations...

Anyay, please use form at https://hosted.weblate.org/hosting/ for
hosting requests.

-- 
	Michal Čihař | http://cihar.com | http://blog.cihar.com

**Comment by GreenLunar** [comment]
No, I want to setup Weblate for /psi-im/psi-translations, but I don't have the necessary privileges to do so.  If Justin would provide me with the necessary privileges, I will gladly do it by myself.

**Comment by nijel** [comment]
Okay, can you please first agree on project level if you actually want to use Weblate?

**Comment by jkarneges** [comment]
Alright I've added a Weblate webhook to this repository, pointing to https://hosted.weblate.org

Let me know if this is not correct or if I need to do anything else.

**Comment by GreenLunar** [comment]
@nijel, is it possible to restrict access to Psi/Translations at https://hosted.weblate.org/ ?
This would be an unpleasant state of affairs, especially to me, if not.

See: MaartenBaert/ssr/issues/351 and nijel/weblate/issues/779

Note: https://github.com/GreenLunar/psi-translations would remain intact until @jkarneges would tell otherwise.

**Comment by GreenLunar** [comment]
Comment by nijel
> Currently this feature is available only for commercial (non public) translations. This might change once nijel/weblate/issues/516 is implemented.

When restricting access would be possible, I will reopen this ticket.

I have asked @crayxt and @hamano to submit their translations using Weblate.  When they would finish, I recommend to cancel hooking Weblate to /psi-im/psi-translations.

I apologies for bothering you, Justin.

**Comment by GreenLunar** [comment]
I have filed the form at https://hosted.weblate.org/hosting/ and I receive notifications in concern to Psi at Weblate, but I am not a project admin.

@crayxt, did you manage to add Kazakh (KK) to Weblate?

**Comment by crayxt** [comment]
@GreenLunar I have requested for Kazakh team creation - and still waiting

**Comment by GreenLunar** [comment]
If I have the proper privileges to approve requested languages, please tell me how.

**Comment by crayxt** [comment]
You better ask weblate admins

**Comment by GreenLunar** [comment]
I will merge pull request #2 within less than two hours.

According to an email message I have received from a Weblate staff member, there is no way, yet, to add new languages for QT TS files from Weblate.  One must create/upload the new file to a repository and a new language will be added in Weblate for that locale.

I will merge pull request #2 within less than two hours.

**Comment by hamano** [comment]
I've completed ja translation :smile:

**Comment by GreenLunar** [comment]
@hamano, did you report your changes to the original author(s)?

I recommend to be coordinated with other translators to get best quality outcomes.

@crayxt, your pull request has been merged; please, continue your work with Weblate.

**Comment by crayxt** [comment]
@GreenLunar finally! Thanks a lot. Do you think about uploading win-installer translations? Does weblate support nsh files?

**Comment by GreenLunar** [comment]
@crayxt, while this is indeed a good suggestion of yours, I am merely a translator, just as you are.  Any question should be directed to [The Psi Team](http://psi-im.org/about/).

I think the Russian developers of Psi are the ones who you should bother.  You can chat with them at Psi+ group chat `xmpp:psi-dev@conference.jabber.ru?join`.

**Comment by GreenLunar** [comment]
It appears it does.

> Weblate supports any translation format understood by Translate-toolkit, however each format being slightly different, there might be some issues with not well tested formats.

From: https://docs.weblate.org/en/latest/formats.html


> NSIS installer: [Existing C++ implementation](http://trac.vidalia-project.net/browser/vidalia/trunk/src/tools)

From: http://docs.translatehouse.org/projects/translate-toolkit/en/latest/formats/index.html

**Comment by GreenLunar** [comment]
It appears it does NOT.

**Comment by GreenLunar** [comment]
Perhaps we can use `nsh2po` and `po2nsh` from Vidalia Project.
https://gitweb.torproject.org/vidalia.git/tree/src/tools

**Comment by hamano** [comment]
@GreenLunar 
In 2008, I knew of  predecessor translator when I have started to translate. But I don't know his contact.
http://psi-im.org/download/lang/ja
Unfortunately, I'm the only one japanese translator from 2008 and beyond.

**Comment by GreenLunar** [comment]
No worries, then, @hamano.  I just do not want to have unpleasant quarrels between translators.

**Comment by GreenLunar** [comment]
> Do you think about uploading win-installer translations? Does weblate support nsh files?

@crayxt, you can send a pull request by yourself, I am almost certain that you would not have any problems to do so at /psi-im/psi.

The reason your submission was on stand still is because I did not allow to myself to do anything in this repository except maintaining my own language.

I have asked to utilize Weblate so others would submit new translations with less hassle, but, unfortunately, until strict access would be possible, I tend to disconnect it.

**Comment by GreenLunar** [comment]
PLEASE DISCONNECT FROM WEBLATE, until further notice.

@nijel, while I appreciate your freedom-driven translation platform, I WILL NOT accept the current state where anyone can intervene with the works of others without being provided with specific permissions to do so.

There is a so called Hebrew translator who has corrupted GNOME and GTK in Hebrew since 2003, and who has been booted out from Hebrew Xfce in recent year. Once Xfce in Hebrew is done, he will be kicked out from MATE and then from GNOME.

That "translator" is well known for corrupting the works of others in Launchpad just so his email address will be inserted in auto-credit field, just so he write that he is a translation contributor in his CV for job application.

Due to his behavior, many Hebrew translators, who DO NOT earn money for contributing translations have left, and, as a result of that, Linux and free software are getting less and less popular amongst Hebrew speakers.

THAT USER DOES NOT USE PSI!

(url of user in question)
https://hosted.weblate.org/user/Yaron/
(will be deleted in edited message)

**Comment by nijel** [comment]
Okay, I've locked the translations for PSI (you could have done it
yourself at https://hosted.weblate.org/projects/psi/#repository).

**Comment by GreenLunar** [comment]
That is too complicated. I would like a permission system, similarly to transifex, or a managing group/team, similarly to Launchpad.

I have my health offended just from seeing the name of that so called translators.

Honestly, the Hebrew translation of Psi is fine, being made by myself, a long term Emacs contributor (Eli Z.) and a Qt contributor (Orgad S.), and the latter even reviewed it.

**Comment by GreenLunar** [comment]
I do not see how I can undo the modifications he did, otherwise than doing so manually.

**Comment by nijel** [comment]
It's git, so it's just matter of git revert in the repository. Or reverting every change in Weblate...

**Comment by GreenLunar** [comment]
But then I would revert the modifications that you, crayxt, and hamano have made, which is not desired by me.  I want to undo changes to a specific language or of a specific author.

**Comment by nijel** [comment]
Weblate does create separate commit for every translation file and author...

**Comment by mvdan** [comment]
Agreed with @nijel - since this is all in git and commits are split by language and author, reverting changes done by bad translators is easy.

**Comment by GreenLunar** [comment]
I am not willing to disturb a repository owner each time someone is vandalizing translation, eventually the owner will have no patience to deal with localization.

**Comment by GreenLunar** [comment]
@jkarneges, please login to hosted.weblate.org, or send me your username there; I would like to add you as Owner.

**Comment by jkarneges** [comment]
Okay I've logged in via github. Username is the same as here.

**Comment by lyn1337** [comment]
Suggestion: Maybe add a link to the description of https://github.com/psi-im/psi-translations ?

**Comment by GreenLunar** [comment]
> Okay I've logged in via github. Username is the same as here.

Done.  Thank you for your time.

> Suggestion: Maybe add a link to the description of https://github.com/psi-im/psi-translations ?

Not yet, until it would be possible to manage user permissions.  Please read my comment [on Jul 24, 2015](https://github.com/psi-im/psi-translations/issues/5#issuecomment-124514022).

**Comment by lyn1337** [comment]
> Not yet, until it would be possible to manage user permissions. Please read my comment on Jul 24, 2015.
@GreenLunar Excuse me, of course I did read your comment. I was unsure if the problem still persisted, since it's been some time. Could do some German translations, if needed.

**Comment by GreenLunar** [comment]
If you do, please submit files in issue tracker or send a pull request.

Once weblate.org would provide us with permission management, we  would use Weblate for translations.
