### ISSUE TITLE
[he] last translation refinements

### ISSUE THREAD

**Issue by GreenLunar** [psi-im/psi-translations#9]
@orgads what word do you prefer for *icon*? (*סמל* or *צלמית*)

If you think *סמל*, please send a commit, if you may.

I have dedicated over an hour for the last commit.

---

*Register new account* should be *רשום חשבון חדש*, not *רישום חשבון חדש*

---

*Author* should be *מחבר*, not *מלחין*

---

~~*Thanks To* could be *תודה לכבוד* or *תודות לכבוד* instead of *תודות*~~ (Rejected by @orgads)

---

*Remove Group* (window title) should be *הסרת קבוצה*, not *הסר קבוצה*
~~*Select Font* (window title) should be *בחירת גופן*, not *בחר גופן*~~ (Qt Core)

---

*if you want Psi to try* may be *אם ברצונך כי Psi ינסה*, instead of *אם ברצונך מן Psi לנסות* 

---

*Valid From* may be *תקפה מאז* or *תקפה מיום*, instead of *תקפה מן*

---

*if you want Psi to replace* may be *אם ברצונך כי Psi יחליף*, instead of *אם ברצונך מן Psi להחליף*

**Comment by GreenLunar** [comment]
Please let me know of anything else to correct.

---

Register new account should be רשום חשבון חדש, not רישום חשבון חדש

---

Author should be מחבר, not מלחין

---

Thanks To could be תודה לכבוד instead of תודות

**Comment by orgads** [comment]
Leave "Thanks To" as תודות

The rest looks good

**Comment by GreenLunar** [comment]
Do you want to write a commit or do you want me to do it?

**Comment by orgads** [comment]
Please do
